### ISSUE TITLE
buildManifest and page obfuscate

### ISSUE THREAD

**Issue by bymagnum** [mtripg6666tdr/nextjs-obfuscator#2]
1. Does not obfuscate _buildManifest.js, when specified in the settings: buildManifest: true 
2. It also does not work recursively by subdirectories, for example, if i18next is installed in the project, the language dependency and pages are in the directory: [language] - it is necessary to finish recursive scanning, as well as the application of settings

Thanks!

**Comment by mtripg6666tdr** [comment]
I'm sorry for the trouble.

> Does not obfuscate _buildManifest.js, when specified in the settings: buildManifest: true

I couldn't reproduce this in the test project included in this repo, could you provide logs by setting `log` option to true?
like:
![image](https://user-images.githubusercontent.com/56076195/187061598-18a0e32d-1ba8-4aa1-87ae-d4d9eebffcd0.png)


> It also does not work recursively by subdirectories, for example, if i18next is installed in the project, the language dependency and pages are in the directory: [language] - it is necessary to finish recursive scanning, as well as the application of settings

I don't know i18next, could you provide a repository (or project) for test to reproduce this?

---
Anyway, you can configure the next.config.js to obfuscate your custom paths by `customMatch:RegExp` option, please also consider to use it.

thank you for your cooperation.

**Comment by mtripg6666tdr** [comment]
Closing the issue due to inactivity. if there's still a bug, please reopen this issue and we can continue addressing the problem. Thank you for your cooperation!
