### ISSUE TITLE
Build failed with webpack error when css filed imported

### ISSUE THREAD

**Issue by choonyme** [mtripg6666tdr/nextjs-obfuscator#23]
Thanks for the nice work. I'm on Nextjs 14.0.3 and am doing an "import '../styles/global.css'" in my /pages/_app.tsx file. This import caused the build process to failed with the messages below. I've tried even emptying the content of global.css and it's still causing error until I remove the import completely. Only nextjs-obfuscator 1.3.0 works so far but not the later versions. Any insight on this?

./src/styles/globals.css
TypeError: Class extends value undefined is not a constructor or null
    at Function.getCssDependency (D:\app\node_modules\next\dist\compiled\mini-css-extract-plugin\index.js:1:8033)
    at addDependencies (D:\app\node_modules\next\dist\compiled\mini-css-extract-plugin\loader.js:1:5836)
    at handleExports (D:\app\node_modules\next\dist\compiled\mini-css-extract-plugin\loader.js:1:6477)
    at D:\app\node_modules\next\dist\compiled\mini-css-extract-plugin\loader.js:1:7631
    at D:\app\node_modules\next\dist\compiled\webpack\bundle5.js:28:814002
    at D:\app\node_modules\next\dist\compiled\webpack\bundle5.js:28:131723
    at symbolIterator (D:\app\node_modules\next\dist\compiled\neo-async\async.js:1:14444)
    at timesSync (D:\app\node_modules\next\dist\compiled\neo-async\async.js:1:5027)
    at Object.eachLimit (D:\app\node_modules\next\dist\compiled\neo-async\async.js:1:14208)
    at D:\app\node_modules\next\dist\compiled\webpack\bundle5.js:28:129914

Import trace for requested module:
./src/styles/globals.css

> Build failed because of webpack errors

**Comment by mtripg6666tdr** [comment]
Hello, I created a new project to look into the issue, but I couldn't replicate it.
Could you provide a reproducible repository or project, or instructions on how to reproduce? Thanks.

**Comment by choonyme** [comment]
Apologies. My fault. Turns out I've used nextjs-obfuscator the wrong way. Was doing the following which was obsolete I guess.

const NextJSObfuscatorPlugin = require("nextjs-obfuscator");

const nextConfig = {
  webpack: (config, {dev}) => {
    if(!dev){
      config.plugins.push(new NextJSObfuscatorPlugin({
        ...nextjsoptions
      }, {
        obfuscateFiles: {
          app: true,
          pages: true,
        },
        log: true,
      }))
    }

    return config;
  }
}

**Comment by mtripg6666tdr** [comment]
I'm glad that the issue was solved. If you have any other issues, please feel free to open a new issue.

**Comment by nakamuraos** [comment]
Hi @mtripg6666tdr,
I have similar problem with this issue.

This repro repo: https://github.com/nakamuraos/next-js-obfuscator-boilerplate

Can you help me check it. Thank you.

**Comment by mtripg6666tdr** [comment]
> Hi @mtripg6666tdr,
> I have similar problem with this issue.
> 
> This repro repo: https://github.com/nakamuraos/next-js-obfuscator-boilerplate
> 
> Can you help me check it. Thank you.

Your repo seems to be configured in the way for nextjs-obfuscator v2.x or lower, so please re-configure it in the right way for v3.x. See the README as a reference.

**Comment by nakamuraos** [comment]
> Your repo seems to be configured in the way for nextjs-obfuscator v2.x or lower, so please re-configure it in the right way for v3.x. See the README as a reference.

Thank you. Just reconfig as v3 and It's working now.
