### ISSUE TITLE
Can't use the plugin

### ISSUE THREAD

**Issue by HenriqueValente09** [mtripg6666tdr/nextjs-obfuscator#24]
This is my code, i'm trying all the paths possible, but it doesn't work

```js
const withNextJsObfuscator = require("nextjs-obfuscator")({}, {
  enabled: "detect",
  patterns: ["./**/*.js", "./*.js", "./**.js", "./public/*.js", "./public/**/*.js"],
  obfuscateFiles: {
    buildManifest: true,
    ssgManifest: true,
    webpack: true,
    additionalModules: ["es6-object-assign"],
  },
  log: true,
});

const nextConfig = withNextJsObfuscator({
  //next config
});
```

**Comment by mtripg6666tdr** [comment]
Could you provide the build log, the expected behavior and the actual behavior. Thanks.

**Comment by HenriqueValente09** [comment]
> Could you provide the build log, the expected behavior, the actual behavior, the next.js version and the plugin version. Thanks.

I have a folder "public" in the same directory, and i want to obfuscate the files in it and the files of the folders as well, this is the log:

`(Plugin) Obfuscated: static/chunks/webpack-14a650d399173556.js 4924 -> 12466
 (Plugin) Obfuscated: static/cRgrQbcZ-90sOYKFQWVMU/_ssgManifest.js 77 -> 1199
 (Plugin) Obfuscated: static/cRgrQbcZ-90sOYKFQWVMU/_buildManifest.js 2073 -> 4350`

**Comment by gspinoza** [comment]
@HenriqueValente09 Make sure your pattern is a regular expression "regex".

Try this one below (Note: if you're using typescript then it should be `"./**/*.tsx"`)
``` js
patterns: ["./**/*.js"],
```
If that doesn't work, try without including any pattern in your pluginOptions. That way it should fallback to the default pattern value.
``` js
const pluginOptions = {
  enabled: true,
  obfuscateFiles: {
    buildManifest: true,
    ssgManifest: true,
    webpack: true,
    additionalModules: ["es6-object-assign"],
    },
  log: true,
 };
```

**Comment by mtripg6666tdr** [comment]
The files in public folder aren't transformed by nextjs's compiler. If you'd like to obfuscate js files placed in the folder, you have to obfuscate manually by [javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator) or something.

**Comment by mtripg6666tdr** [comment]
Closing due to housekeeping purpose. If you still have been experiencing the problem, please reopen the issue.
