### ISSUE TITLE
NextJS 15 support?

### ISSUE THREAD

**Issue by mr-tm** [mtripg6666tdr/nextjs-obfuscator#34]
NextJS 15 was recently released: https://nextjs.org/blog/next-15 
Does this plugin support NextJS 15?

**Comment by mtripg6666tdr** [comment]
Thank you for reporting the issue. We will investigate if this works fine with the new version (and fix issues as needed) in a few days.

**Comment by mtripg6666tdr** [comment]
Now released new version that supports next v15. If you have any problems, please report it.
