### ISSUE TITLE
Code-splitted chunks are not obfuscated

### ISSUE THREAD

**Issue by Pikachews** [mtripg6666tdr/nextjs-obfuscator#8]
Code-splitted chunks that are shared between pages are not obfuscated and there is no setting to enable obfuscating these files.
E.g. `static/chunks/226-7acfb228cf0d3e2c.js`

**Comment by mtripg6666tdr** [comment]
I just implemented this in #13 but immediately I found obfuscating splitted chunks causes the nextjs app broken :sob:

**Comment by Pikachews** [comment]
Hm, perhaps it depends on the complexity or features of the app. When I had tested obfuscating chunks on my app (I had attempted to implement it via a patch, using the same approach in #13), it seemed that everything worked properly, even with **all** of the obfuscation options enabled. For reference, I am using nextjs 13.4.4.
Thanks for implementing this!
