### ISSUE TITLE
Sourcemaps not emitted, even with `sourceMap: true`

### ISSUE THREAD

**Issue by Pikachews** [mtripg6666tdr/nextjs-obfuscator#9]
Files that are passed to the obfuscator do not have their sourcemaps emitted/saved, even if `sourceMap: true` is set in the `javascript-obfuscator` options.

**Comment by mtripg6666tdr** [comment]
I just implemented this in #13 but immediately I found obfuscating splitted chunks causes the nextjs app broken :sob:

**Comment by mtripg6666tdr** [comment]
Thanks for the issue. The current way of hooking, i don't think the source-map can be supportted. If the new strategy to obfuscate files (#13) is implemented and shipped, this might be performed.

**Comment by mtripg6666tdr** [comment]
I found how to handle source-maps with the v1.x's way of obfuscation and I implemented in v1.3.1.
